[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]

# WARNING: Allows Foundry to execute scripts on host system
# Comment out if not in use
# Old/nuclear way
# ffi = true

# Least privileged access
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
